name: eyehandcal
channels:
  - pytorch
  - fair-robotics
  - aihabitat
  - conda-forge
  - defaults
dependencies:
  - pip
  - pybind11
  - python=3.8
  - libopencv=4.5.3
  - polymetis=714_g1a617e97=py38_714
  - librealsense=2.50.0
  - scipy
  - tqdm
  - pip:
    - gtsam
